apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-microservice.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-microservice.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-microservice.name" . }}
    spec:
      containers:
      - name: my-microservice
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: SSM_PARAM
          value: "/my-microservice/message"
