apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-microservice.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
  selector:
    app: {{ include "my-microservice.name" . }}
